---
keys:
  - &admin_amchelle BAB0CD1FE6F28A831C7C2856E42DD3602C85D13A
  - &server_elaine 25ba07ec6d5fbc69f9a42b78d9457a224f54574a
creation_rules:
  - path_regex: secrets/main\.yaml$
    key_groups:
    - pgp:
      - *admin_amchelle
      - *server_elaine
